apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: frontend-starter-app
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: frontend-starter-app
    app.kubernetes.io/part-of: frontend-starter-app
  name: frontend-starter-app
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: frontend-starter-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: frontend-starter-app
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/mmarosi123-tenant/frontend-starter-app/frontend-starter-app@sha256:136b34abc1d7fde4b9979a836eab10a49bebc9f2a79395fa73efedd8bc8b0e20
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
