apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: frontend-starter-app
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: frontend-starter-app
    app.kubernetes.io/part-of: frontend-starter-app
  name: frontend-starter-app
spec:
  ports:
  - name: "3001"
    port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: frontend-starter-app
status:
  loadBalancer: {}
